name: Build Flutter APK

on:
  push:
    branches: [ main ]
permissions:
  contents: write

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Accept Android SDK Licenses and Install NDK
        run: |
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
          
          echo "📦 Installing required NDK version..."
          yes | sdkmanager "ndk;29.0.13113456"
          
          echo "✅ Accepting all licenses..."
          yes | sdkmanager --licenses

          echo "📜 Installed SDK packages:"
          sdkmanager --list

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release
      - name: Extract version from pubspec.yaml
        id: extract_version
        run: |
          version=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f2 | tr -d '\r')
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/flutter-apk/app-release.apk
          tag: v${{ env.VERSION }}
          name: "Release v${{ env.VERSION }}"
          body: "Automated release for version ${{ env.VERSION }}"
          token: ${{ secrets.GITHUB_TOKEN }}
